language: node_js

env: 
  - NODE_ENV=test DB_MIGRATION=true DB_URL=postgres://postgres@127.0.0.1:5432/test-api

node_js:
  - "6.5"

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database "test-api";' -U postgres

script: 
  - npm test