language: node_js

env: 
  - NODE_ENV=test DATABASE_MIGRATION=true DATABASE_URL=postgres://postgres@127.0.0.1:5432/rest-api-test

node_js:
  - "6.5"

addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5

before_script:
  - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -U postgres -c 'create database "rest-api-test";'

script: 
  - npm run lint
  - npm test